kind: pipeline
name: default

steps:
- name: render-worker
  image: node:22
  volumes:
  - name: cache
    path: /drone/src/node_modules
  environment:
    NITRO_PRESET: "cloudflare_pages"
  commands:
  - npm install
  - npm run build
- name: render-static
  image: node:22
  volumes:
  - name: cache
    path: /drone/src/node_modules
  environment:
    NITRO_PRESET: "static"
  commands:
# - npm install
  - npm run generate
- name: build-project
  image: node:22
  commands:
  - cp -r dist/_worker.js .output/public/
  - rm -r dist
  - mv .output/public dist
  - cp _routes.json dist
- name: deploy-to-cloudflare
  image: node:22
  environment:
    CLOUDFLARE_ACCOUNT_ID:
      from_secret: KUPTZ_CLOUDFLARE_ACCOUNT_ID
    CLOUDFLARE_API_TOKEN:
      from_secret: CLOUDFLARE_API_TOKEN
  volumes:
  - name: cache
    path: /drone/src/node_modules
  commands:
  - npx wrangler pages deploy ./dist --project-name=tools-kup-tz

trigger:
  event:
  - tag
  - custom

volumes:
- name: cache
  host:
    path: /tmp/drone/website
